name: CI

on:
  push:
    branches:
      - '*'
      - main
  pull_request:
    branches:
      - main

jjobs:
  change:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"

      - name: "Get yarn cache path"
        id: "yarn-cache"
        run: 'echo "::set-output name=dir::$(yarn cache dir)"'
        shell: "bash"

      - name: "Enable node"
        uses: "actions/setup-node@master"
        with:
          node-version: "14.x"

      - name: "Load yarn cache"
        uses: "actions/cache@v2"
        with:
          path: "${{ steps.yarn-cache.outputs.dir }}"
          key: "${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: "Install dependencies"
        run: "yarn install --frozen-lockfile"

      - name: "Run checks"
        uses: "./.github/actions/check"

      - name: "Build"
        run: "yarn build"

      - name: "Changesets: version or release"
        uses: "changesets/action@main"
        with:
          publish: "yarn release"
          commit: "ci(release): version packages"
        env:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.SEMANTIC_RELEASE_TOKEN }}"
  # chromatic-deployment:
  #   runs-on: ubuntu-latest
  #   # Job steps
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install dependencies
  #       run: yarn
  #     - name: Publish to Chromatic
  #       uses: chromaui/action@v1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

